### PR TITLE
Fixes validation errors #16

### LINKED ISSUE #16: Validation warning during deployment
Getting following validation warning during deployment

> Serverless: Configuration warning:
> Serverless:   at 'functions.category.events[0].http': unrecognized property 'reqValidatorName'
> Serverless:   at 'functions.category.events[0].http': unrecognized property 'documentation'

I have added the following to package.json dependencies

> "serverless-aws-documentation": "^1.1.0",
> "serverless-reqvalidator-plugin": "^1.0.3"

	
And the plugins to serverless.yaml file

> plugins:
>   - serverless-reqvalidator-plugin
>   - serverless-aws-documentation

  
The warning comes when running 'sls deploy' command.

According to this documentation, this warning comes when serverless tries to validate the configuration using AJV and the configuration does not meet expectation. 
https://www.serverless.com/framework/docs/configuration-validation/

Does the plugin need to extend validation schema?
https://www.serverless.com/framework/docs/providers/aws/guide/plugins/#extending-validation-schema

### PR DESCRIPTION
**Pull request by RafPe**
* Fix #16 by adding validation definition for extended property

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -46,6 +46,14 @@ class ServerlessReqValidatorPlugin {
 
     this._beforeDeploy = this.beforeDeploy.bind(this)
 
+    // Create schema for your properties. For reference use https://github.com/ajv-validator/ajv
+    serverless.configSchemaHandler.defineFunctionEventProperties('aws', 'http', {
```
Comment (medington) [inline src/index.js:50]: With the 1.0.4 release I'm now getting this error when starting our application:

```TypeError: Cannot read property 'defineFunctionEventProperties' of undefined```

Is there a dependent package that needs to be added?

Comment (RafPe) [reply src/index.js:50]: What framework version are your running ?

Comment (medington) [reply src/index.js:50]: Hi, thanks for the response. Our repo (which is private), is actually locked to severless 1.74 due to another issue. I can revisit that and determine if that still exists.
